
# All of the starting information for the roomates
static_roomies = [
    {'name':'Isaac', 
      'charge_on_venmo' : False,
      'base_rent' : 486,
      'rent_balance' : 0,
      'util_balance' : 0},
    {'name':'Dieter', 
      'charge_on_venmo' : True,
      'venmo_name' : 'klemchowda',
      'base_rent' : 486,
      'rent_balance' : 0,
      'util_balance' : 0},
    {'name':'Faris', 
      'charge_on_venmo' : True,
      'venmo_name' : 'farisdizdarevic',
      'base_rent' : 486,
      'rent_balance' : 0,
      'util_balance' : 0},
    {'name':'Justin', 
      'charge_on_venmo' : True,
      'venmo_name' : 'kimsjustin',
      'base_rent' : 486,
      'rent_balance' : 0,
      'util_balance' : 0},
    {'name':'Amr', 
      'charge_on_venmo' : True,
      'venmo_name' : 'AmrDowair',
      'base_rent' : 486,
      'rent_balance' : 0,
      'util_balance' : 0},
    {'name':'Jake', 
      'charge_on_venmo' : True,
      'venmo_name' : 'Jacob-Oestreich',
      'base_rent' : 486,
      'rent_balance' : 0,
      'util_balance' : 0},
    {'name':'Matt', 
      'charge_on_venmo' : True,
      'venmo_name' : 'Matt-Dolan-5',
      'base_rent' : 476,
      'rent_balance' : 0,
      'util_balance' : 0},
    {'name':'Zac', 
      'charge_on_venmo' : False,
      'base_rent' : 486,
      'rent_balance' : 0,
      'util_balance' : 0},
    {'name':'Marc', 
      'charge_on_venmo' : False,
      'base_rent' : 411,
      'rent_balance' : 0,
      'util_balance' : 0},
    {'name':'Alex', 
      'charge_on_venmo' : False,
      'base_rent' : 411,
      'rent_balance' : 0,
      'util_balance' : 0}]


